# Generated by Django 4.1 on 2022-08-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='', verbose_name='uploads/banners')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
